services:
  postgres-dev:
    image: postgres:latest
    restart: always
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - ./backend/services/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - PGPORT=${PGPORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      database-network:
        aliases:
          - database
  
  backend-api:
    build: "./backend"
    restart: always
    depends_on:
      postgres-dev:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - PGPORT=${PGPORT}
      - PORT=${PORT}
      - JWT_KEY=${JWT_KEY}
    networks:
      database-network:
        aliases:
          - backend

networks:
  database-network:
    name: database-network