services:
  postgres-dev:
    image: postgres:latest
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - ./backend/services/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/dev-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - PGPORT=${PGPORT}
    networks:
      database-network:
        aliases:
          - database

networks:
  database-network:
    name: database-network