services:
  postgres-dev:
    image: postgres:latest
    restart: always
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - ./backend/services/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - PGPORT=${PGPORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      database-network:
        aliases:
          - database-dev

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./backend/services/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - PGPORT=${PGPORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      database-network:
        aliases:
          - database
  
  backend-api:
    build: "./backend"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - PGPORT=${PGPORT}
      - PORT=${PORT}
      - JWT_KEY=${JWT_KEY}
    networks:
      database-network:
        aliases:
          - backend
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      kafka-network:
        aliases:
          - zookeeper
    
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      kafka-network:
        aliases:
          - kafka

networks:
  database-network:
    name: database-network
  kafka-network:
    name: kafka-network